worker_app: synapse.app.pusher
worker_name: worker_pusher

# The replication listener on the main synapse process.
worker_replication_host: 127.0.0.1
worker_replication_http_port: 9093

worker_log_config: /etc/matrix-synapse/workers/workers_log_config.yaml
