worker_app: synapse.app.frontend_proxy
worker_name: worker_frontend_proxy

# The replication listener on the main synapse process.
worker_replication_host: 127.0.0.1
worker_replication_http_port: 9093

worker_main_http_uri: http://127.0.0.1:8008

worker_listeners:
 - type: http
   port: 8088
   resources:
     - names:
       - client

worker_log_config: /etc/matrix-synapse/workers/workers_log_config.yaml
